version: "3.8"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: latest_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my_database"
    volumes:
      - /home/docker/:/docker/
